import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarUser from "@/Components/Shared/NavbarUser";
import FooterUser from "@/Components/Shared/FooterUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="Light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavbarUser></NavbarUser>
        <main>{children}</main>
        <FooterUser></FooterUser>
      </body>
    </html>
  );
}
